### ISSUE TITLE
Stop using app-localize-behavior-fork when IE10 dies

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-navigation-ui#125]
We're currently [using a fork](https://github.com/Brightspace/app-localize-behavior) of Polymer's [app-localize-behavior](https://github.com/PolymerElements/app-localize-behavior) due to a JavaScript error that occurs in IE10.

I've [raised the defect](https://github.com/PolymerElements/app-localize-behavior/issues/29) with Polymer and [submitted a PR](https://github.com/PolymerElements/app-localize-behavior/pull/30), but until that gets merged in, or we no longer need to support IE10 (January 2017), we'll need to keep using the fork.

This issue is just tracking that eventual switchover from the fork back to `app-localize-behavior` actual.

**Comment by ryantmer** [comment]
Oh - this was fixed in #231, yes?

**Comment by dlockhart** [comment]
Indeed, thanks!
