### ISSUE TITLE
Escape from dropdown doesn't put focus on opener

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-navigation-ui#73]
@dbatiste: not sure if this is an issue with dropdown or how we're using it.

Steps to reproduce:
1. Tab to one of our openers (e.g. personal menu)
2. Press enter, dropdown opens and focus moves to the dropdown
3. Press escape, dropdown closes but focus is lost

Expected behaviour: focus should be put back on the opener.

**Comment by dbatiste** [comment]
Thanks.  I thought I'd handled this but it looks like I only addressed it for the dropdown-menu.  I think I can factor the logic so that it applies to both it and the generic dropdown.

**Comment by dlockhart** [comment]
Cool, closing this then and [created a defect in d2l-dropdown](https://github.com/Brightspace/d2l-dropdown-ui/issues/24)
