### ISSUE TITLE
Clicking dropdown opener should close it

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-navigation-ui#74]
@dbatiste: not sure if this is a dropdown thing or us, or maybe it's a good argument to create a "dropdown opener" behaviour

Steps to reproduce:
1. Click on a dropdown opener (e.g. personal menu), dropdown opens
2. Click on the opener again, dropdown closes, then opens again

Expected behaviour: dropdown should close, focus should remain on the opener

**Comment by dbatiste** [comment]
Yep - agreed.  I think this is an opener-behavior.

**Comment by dbatiste** [comment]
Addressed with recent updates to `d2l-dropdown` and it's openers.
