### ISSUE TITLE
highlight boxes and notification indicators are clipped in IE

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-navigation-ui#99]
In IE, the notification indicator is getting clipped by the edge of the notification area:

![bell-notification-dot](https://cloud.githubusercontent.com/assets/5491151/15973995/37269ce4-2f14-11e6-859e-92918aaef59e.PNG)

Also, the highlight boxes:

![screen shot 2016-06-21 at 9 03 18 am](https://cloud.githubusercontent.com/assets/5491151/16230359/185819ea-378f-11e6-82f3-ec17531ac269.png)

**Comment by njostonehouse** [comment]
Looks fine in Edge
